#!/usr/bin/env bash

current_branch="$(git rev-parse --abbrev-ref HEAD)"


# regex to validate in commit msg
commit_regex='^((feat|fix|doc|refactor\W#[0-9]+\W\w)|merge).*'
error_msg="Aborting commit. Your commit message is missing either a prefix (feat,fix,doc,refactor) #<issue> or 'Merge'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
